# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a097fbd15de094d4170bde23543f6b5bc0b9ea4d11fad526d379c455e879e36aa22c4ee038265d2766c5876f991a5590562a998fd4486a54d835c2d38badff9f

test:
  secret_key_base: 1b89b994f0524e4bf3cf1acb16774b8652fa7f3fd171b6bbc745271c5ffa2709f4e74e40ccb85520947f5cadeab208ebf0bc4b4ce19d79cf46ab1685942cd3ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
